const cardsPic=[
  {
    id:1,
    image:"./jscript2&3-project-pic/1.jpg",
    counter:0
    
  },
  {
    id:2,
    image:"./jscript2&3-project-pic/2.jpg",
    counter:0
  },
  {
    id:3,
    image:"./jscript2&3-project-pic/3.jpg",
    counter:0
  },
  {
    id:4,
    image:"./jscript2&3-project-pic/4.jpg",
    counter:0
  },
  {
    id:5,
    image:"./jscript2&3-project-pic/5.jpg",
    counter:0
  },
  {
    id:6,
    image:"./jscript2&3-project-pic/6.jpg",
    counter:0
  },
  {
    id:7,
    image:"./jscript2&3-project-pic/7.jpg",
    counter:0
  },
  {
    id:8,
    image:"./jscript2&3-project-pic/8.jpg",
    counter:0
  },
  {
    id:9,
    image:"./jscript2&3-project-pic/9.jpg",
    counter:0
  }
]
